services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ddd-schedule-app-web
    restart: unless-stopped
    working_dir: /opt/src
    volumes:
      - ./src:/opt/src
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: ddd-schedule-app-nginx
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./src:/opt/src
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: ddd-schedule-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  test_db:
    image: mysql:8.0
    container_name: ddd-schedule-app-test-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test_laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - test_dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: ddd-schedule-app-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  test_dbdata:
